import type { Metadata } from "next";
import "./globals.css";
import { SelectionProvider } from "@/components/SelectionProvider";
import QueryProvider from "@/components/QueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <QueryProvider>
          <SelectionProvider>{children}</SelectionProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
