name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install PHP dependencies
        run: composer install
        working-directory: modules/growset

      - name: Run PHPUnit
        run: |
          if [ -f vendor/bin/phpunit ]; then
            vendor/bin/phpunit
          else
            echo "phpunit not found, skipping"
          fi
        working-directory: modules/growset

      - name: Lint PHP
        run: find modules -name "*.php" -print0 | xargs -0 -n1 php -l

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Node dependencies
        run: npm ci
        working-directory: frontend

      - name: Lint
        run: npm run lint
        working-directory: frontend

      - name: Build and export
        run: npm run build:export
        working-directory: frontend

      - name: Upload exported assets
        uses: actions/upload-artifact@v4
        with:
          name: exported-assets
          path: modules/growset/assets
